FitnessStudioUI/Models/ErrorViewModel.cs
using System;

namespace FitnessStudioUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FitnessStudioUI/Controllers/CustomerAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FitnessStudioApp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace FitnessStudioUI.Controllers
{
    [Authorize]
    public class CustomerAccountsController : Controller
    {
        // GET: CustomerAccounts
        public IActionResult Index()
        {
            return View(FitnessStudio.GetAccountInfoByEmailAddress(HttpContext.User.Identity.Name));
        }

        // GET: CustomerAccounts/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerAccount = FitnessStudio.GetAccountInfoByCustomerID(id.Value);
            if (customerAccount == null)
            {
                return NotFound();
            }

            return View(customerAccount);
        }

        // GET: CustomerAccounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CustomerAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CustomerName,EmailAddress,CustomerPhone,DateofBirth")] CustomerAccount customerAccount)
        {
            if (ModelState.IsValid)
            {
                FitnessStudio.CreateAccount(customerAccount.CustomerName, customerAccount.EmailAddress, customerAccount.CustomerPhone, customerAccount.DateofBirth);
                return RedirectToAction(nameof(Index));
            }
            return View(customerAccount);
        }

        // GET: CustomerAccounts/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerAccount = FitnessStudio.GetAccountInfoByCustomerID(id.Value);
            if (customerAccount == null)
            {
                return NotFound();
            }
            return View(customerAccount);
        }

        // POST: CustomerAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("CustomerID,CustomerName,EmailAddress,CustomerPhone,DateofBirth")] CustomerAccount customerAccount)
        {
            if (id != customerAccount.CustomerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                FitnessStudio.Update(customerAccount);
                return RedirectToAction(nameof(Index));
            }
            return View(customerAccount);
        }
        public IActionResult GetClassPass(int? id)
        {
            var account = FitnessStudio.GetAccountInfoByCustomerID(id.Value);
            return View(account);

        }
        [HttpPost]
        public IActionResult GetClassPass(IFormCollection controls)
        {
            var custID = Convert.ToInt32(controls["CustomerID"]);
            var classtitle = Enum.Parse<TitleOfClass>(controls["ClassTitle"]);
            var classpassOption = Enum.Parse<ClassPassOption>(controls["TypeOfClassPass"]);
            FitnessStudio.BuyAClassPass(custID, classtitle, classpassOption);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Membership(int? id)
        {
            var account = FitnessStudio.GetAccountInfoByCustomerID(id.Value);
            return View(account);

        }
        [HttpPost]
        public IActionResult Membership(IFormCollection controlsMembership)
        {
            var CustID = Convert.ToInt32(controlsMembership["CustomerID"]);
            var membershipType = Enum.Parse<MembershipOption>(controlsMembership["TypeOfMembership"]);
            FitnessStudio.BuyAMembership(CustID, membershipType);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Transactions(int? id)
        {
            var transactions = FitnessStudio.GetAllTransactionsByCustomerID(id.Value);
            return View(transactions);
        }
    }
}

FitnessStudioUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FitnessStudioUI.Models;

namespace FitnessStudioUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FitnessStudioUI/Views/CustomerAccounts/Create.cshtml
@model FitnessStudioApp.CustomerAccount

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CustomerAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhone" class="control-label"></label>
                <input asp-for="CustomerPhone" class="form-control" />
                <span asp-validation-for="CustomerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateofBirth" class="control-label"></label>
                <input asp-for="DateofBirth" class="form-control" />
                <span asp-validation-for="DateofBirth" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FitnessStudioUI/Views/CustomerAccounts/Delete.cshtml
@model FitnessStudioApp.CustomerAccount

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateofBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateofBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfClassPass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfClassPass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfMembership)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfMembership)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MembershipExpires)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MembershipExpires)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerSince)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerSince)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FitnessStudioUI/Views/CustomerAccounts/Details.cshtml
@model FitnessStudioApp.CustomerAccount

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CustomerAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateofBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateofBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfClassPass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfClassPass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfMembership)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfMembership)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MembershipExpires)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MembershipExpires)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerSince)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerSince)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CustomerID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FitnessStudioUI/Views/CustomerAccounts/Edit.cshtml
@model FitnessStudioApp.CustomerAccount

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CustomerAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerID" />
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhone" class="control-label"></label>
                <input asp-for="CustomerPhone" class="form-control" />
                <span asp-validation-for="CustomerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateofBirth" class="control-label"></label>
                <input asp-for="DateofBirth" class="form-control" />
                <span asp-validation-for="DateofBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FitnessStudioUI/Views/CustomerAccounts/GetClassPass.cshtml
@model FitnessStudioApp.CustomerAccount

@{
    ViewData["Title"] = "GetClassPass";
}

<h1>GetClassPass</h1>

<h4>CustomerAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="GetClassPass">

            <input type="hidden" asp-for="CustomerID" />

            <div class="form-group">
                <label asp-for="ClassTitle" class="control-label"></label>
                <select asp-for="ClassTitle" asp-items="Html.GetEnumSelectList<TitleOfClass>()"class="form-control"></select>
                
            </div>
            <div class="form-group">
                <label asp-for="TypeOfClassPass" class="control-label"></label>
                <select asp-for="TypeOfClassPass" asp-items="Html.GetEnumSelectList<ClassPassOption>()" class="form-control"></select>
              
            </div>
         <div class="form-group">
                <input type="submit" value="Buy" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FitnessStudioUI/Views/CustomerAccounts/Index.cshtml
@model IEnumerable<FitnessStudioApp.CustomerAccount>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateofBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MembershipExpires)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerSince)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateofBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MembershipExpires)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerSince)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CustomerID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CustomerID">Details</a> |
                <a asp-action="GetClassPass" asp-route-id="@item.CustomerID">ClassPass</a> |
                <a asp-action="Membership" asp-route-id="@item.CustomerID">Membership</a> |
                <a asp-action="Transactions" asp-route-id="@item.CustomerID">Transactions</a>
            </td>
        </tr>
}
    </tbody>
</table>

FitnessStudioUI/Views/CustomerAccounts/Membership.cshtml
@model FitnessStudioApp.CustomerAccount

@{
    ViewData["Title"] = "Membership";
}

<h1>GetClassPass</h1>

<h4>CustomerAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Membership">

            <input type="hidden" asp-for="CustomerID" />

            <div class="form-group">
                <label asp-for="TypeOfMembership" class="control-label"></label>
                <select asp-for="TypeOfMembership" asp-items="Html.GetEnumSelectList<MembershipOption>()" class="form-control"></select>

            </div>

            <div class="form-group">
                <input type="submit" value="Buy" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FitnessStudioUI/Views/CustomerAccounts/Transactions.cshtml
@model IEnumerable<FitnessStudioApp.Transaction>

@{
    ViewData["Title"] = "Transactions";
}

<h1>Transactions</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TransactionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransactionType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerAccount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerAccount.CustomerName)
            </td>
            <td>

            </td>
        </tr>
}
    </tbody>
</table>

FitnessStudioUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FitnessStudioUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitnessStudioUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Fitness Studio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerAccounts" asp-action="Index">Customer Account</a>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FitnessStudioUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>